name: proto
description: A sample command-line application.
version: 1.0.0
publish_to: "none"
# homepage: https://www.example.com

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  fixnum: ^1.0.1
  protobuf: ^2.1.0

dev_dependencies:
  test: ^1.16.0
